Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,31 +15,34 @@ jobs:
       - name: List directory contents
         run: ls -la  # List files in the working directory
 
-      - name: Set up Node.js
-        shell: bash
+
+      - name: Set up nvm
         run: |
-          if ! nvm ls 20 > /dev/null 2>&1; then 
-            echo "Node.js is not installed. Installing..."
+          # Install nvm
+          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
+          # Source nvm
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          # Check if Node.js is installed
+          if ! command -v node &> /dev/null; then
+            echo "Node.js could not be found. Installing..."
             nvm install 20
-          else 
-            echo "Node.js is already installed."
+          else
+            echo "Node.js is installed"
           fi
-
-      # - name: Set up nvm
-      #   run: |
-      #     # Install nvm
-      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
-      #     # Source nvm
-      #     export NVM_DIR="$HOME/.nvm"
-      #     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-      #     # Check if Node.js is installed
-      #     if ! command -v node &> /dev/null; then
-      #       echo "Node.js could not be found. Installing..."
-      #       nvm install 20
-      #     else
-      #       echo "Node.js is installed"
-      #     fi
-
+      - name: Create .releaserc.json if not exists
+        run: |
+          if [ ! -f .releaserc.json ]; then
+            echo '{
+              "branches": ["main"],
+              "plugins": [
+                "@semantic-release/commit-analyzer",
+                "@semantic-release/release-notes-generator",
+                "@semantic-release/npm",
+                "@semantic-release/github"
+              ]
+            }' > .releaserc.json
+          fi
     
         # Specify your Node.js version
 
